### ISSUE TITLE
Unable to handle time change for this Sunday on daily forecasts

### ISSUE THREAD

**Issue by morian** [bugsounet/MMM-MeteoFrance#47]
We have a time change in France this Sunday, and daily forecasts break the whole module.
The issue resides in `searchDate`, which create a new Date at 14:00, and then increment from here:
- https://github.com/bugsounet/MMM-MeteoFrance/blob/06e94f9a913ee22c3d457a2a2d3caa4634c26a39/MMM-MeteoFrance.js#L256

This fits well because MeteoFrance always generate a report at 12:00 UTC even after 5 days.
I suggest getting rid of the whole manual Date processing and move to using moment everywhere since it is already included.

A patch suggestion will follow.

**Comment by bugsounet** [comment]
Thanks for this PR, it's merged :)
